excerpt_separator: ""
#pygments: true
markdown: kramdown
url: https://a5s7.xyz
enforce_ssl: a5s7.xyz
title: Anton Stukalo
tagline: Yet Another Software Engineer's blog
description: Technical posts on software engineering by Anton Stukalo
paginate: 5

permalink: pretty

author:
  name: 'Anton Stukalo'
  url: https://a5s7.xyz

disqus_shortname: 'astukalo'
exclude: [Gemfile, Gemfile.lock, README.MD]

pages:
  Tags: '/tags'

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

excerpt_separator: <!--more-->

# Theme
theme:
  # Localization Strings
  str_continue_reading: "Continue reading..."